### ISSUE TITLE
Using PBX as middleware (connect/express)?

### ISSUE THREAD

**Issue by PandaWhisperer** [pandastrike/pbx#10]
I found myself wanting to add certain features to a PBX server, such as logging. 

Then I realized that there's already solutions to that, and there is no need for us to reinvent the wheel and build another logger, if we could just mount PBX as middleware into connect or express.

The work involved should be minimal, since the processor already returns a `function(request, response)`. All that's needed would be taking a `next` parameter and calling it after a request was processed.

Perhaps we could add a `middleware` function to the processor that returns a middleware instead of a request handler?

**Comment by PandaWhisperer** [comment]
Actually, after reading up more on this, it seems that handling `next` isn't really necessary, since presumably PBX will end the request/response cycle. In fact, the current result of running the processor can be mounted into a express/connect app just fine and it will work.

I'm not sure at this point if it still makes sense to add awareness for a `next` parameter. There may be examples of middleware that one would want to run AFTER PBX, but I can't come up with any right now.

**Comment by dyoder** [comment]
I don't want to include anything beyond support for the Node API.

I don't want to encourage people to use Express or Connect. And if people really want to, as you say, it's trivial to add a middleware wrapper around a PBX processor.

Please familiarize yourself with [the roadmap for Patchboard/PBX](https://github.com/pandastrike/panda-wiki/blob/master/projects/foss/patchboard/roadmap.md). You'll find that we have a plan for adapting the processing. We also plan to have most of the basics covered by default.

See specifically the sections on [strategies](https://github.com/pandastrike/panda-wiki/blob/master/projects/foss/patchboard/roadmap.md#strategies) and [proxies](https://github.com/pandastrike/panda-wiki/blob/master/projects/foss/patchboard/roadmap.md#proxies).

**Comment by dyoder** [comment]
I should add, for the record, there's nothing _wrong_ with using Express or Connect or using PBX with those frameworks. However, in our experience, there are some issues with middleware that we plan to address with a different approach (the aforementioned strategies and proxies).

**Comment by PandaWhisperer** [comment]
Alright. I get that there are _problems_ with the middleware approach, but at least it's refreshingly simple. I read the part about Strategies and it's rather vague at the moment. Also it sounds like a lot more heavyweight approach, especially when we're talking about re-implementing the context in order to gain the ability to modify the request.

FWIW, express-style middlewares already exist to solve a lot of common tasks, they're (presumably) well tested and could easily be combined with PBX. Supporting those frameworks could also help adoption, as it's easier to sell devs and managers on something that works with they already know and trust, rather than having to convince them to throw all of their code away and learn a completely new tool from scratch.

Just my 2 cents. But I'm looking forward to having my mind blown by what you've got in store.

**Comment by automatthew** [comment]
Patchboard should be usable with middleware, but should also be completely ignorant of it.

**Comment by PandaWhisperer** [comment]
Alright @automatthew, I think that's already the case. I'm going to close this issue.
