### ISSUE TITLE
`respond` does not work for arrays

### ISSUE THREAD

**Issue by PandaWhisperer** [pandastrike/pbx#13]
## Summary

Calling `respond` with an array does not work.
## Example

Using the following handler:

``` coffeescript
   test:
     get: async ({respond}) ->
       respond 200, []
```

Invoking the handler causes an Internal Server Error and the following message on the server console:

```
TypeError: first argument must be a string or Buffer
```

The location from the stack trace resolves to [src/context.coffee#L53](https://github.com/pandastrike/pbx/blob/master/src/context.coffee#L53).
## Expected result

The server should respond with a successful status and an empty array in the response body.

**Comment by PandaWhisperer** [comment]
This is caused by a false dichotomy in [src/context.coffee#L48-L53](https://github.com/pandastrike/pbx/blob/master/src/context.coffee#L48-L53):

``` coffeescript
      if type(content) == "object"
        response.write (JSON.stringify content, null, 2)
      else
        response.write content
```

This assumes that everything that isn't an object must be a string. 

Since line 48 is using fairmont's `type` function, instead of the standard `typeof` operator, there are [more possible cases](https://github.com/pandastrike/fairmont/blob/master/src/type.litcoffee#type) than just "object" and "string". 

Actually, even with `typeof`, [there are a few more](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof). 

### Possible Fixes

`response.write`, according to its error message, expects a string or a Buffer. Hence, if `content` is of either of those types, we can safely pass it along. **In all other cases**, we need to convert it to a string (or Buffer).

I had a few more ideas, but that seems to be the best, as in most simple and safest. I'll submit a PR.

**Comment by PandaWhisperer** [comment]
Actually, I just noticed this is also imperfect in a few cases:
- Regexps: `JSON.stringify /test/` returns `{}` 
- Functions: `JSON.stringify () ->` returns `undefined`
- Streams: not sure what happens when you try to stringify a stream. A note above the code says we want to eventually be able to respond with streams as well.

It still seems like the best stop gap solution.

**Comment by automatthew** [comment]
Regexes, functions, and streams don't have representations suitable for serialization in a response body.

We probably want to allow functions and streams as args to the `respond` method, at least eventually.   Functions should return a string.  Streams should do whatever streams should do.

**Comment by PandaWhisperer** [comment]
[HTTP responses are `WriteableStream`s](https://nodejs.org/api/http.html#http_class_http_serverresponse), so there should be an easy way to pipe another stream in there, no?

With regards to regexes and functions, actually, you can call `toString()` on them to get a serialization. For regexes, this produces something like `/test/`. For functions, well, you know what it does. The latter is probably a bad idea though, so perhaps invoking the function and checking for a string result might be a way to go, but I can't think of a situation where this would be useful. If you have something async to do to produce the respond, you can just `yield` to it.

**Comment by automatthew** [comment]
I cannot think of a situation where a Regex provides appropriate response content for an HTTP request.

**Comment by PandaWhisperer** [comment]
Me neither, just throwing it out there.

So what should be the appropriate response in those cases? Throw an exception?

**Comment by automatthew** [comment]
I think throwing an exception is appropriate for anything that we don't explicitly decide to handle.  But we'd need to make sure that this results in a 500 error to the client, rather than server crashing.

**Comment by PandaWhisperer** [comment]
With regards to streams, if I read [the documentation correctly](https://nodejs.org/api/stream.html#stream_readable_pipe_destination_options), it should be as easy as doing 

``` coffeescript
if content instanceof stream.Readable
  response.pipe(content)
```

**Comment by PandaWhisperer** [comment]
It currently already produces a 500 error, and the server doesn't crash.

**Comment by PandaWhisperer** [comment]
@automatthew could you help me build a test for these scenarios?

**Comment by automatthew** [comment]
It'll be a few days before I have spare time, sadly.

**Comment by dyoder** [comment]
`help wanted` :)

basically if it isn't a string or a stream we should simply call `stringify`. i don't much care about the nuances past that. If you're going to try to send a function or a regexp as content, things are going awry one way or another. later, we may want to go back through and add argument checking everywhere, but i don't think that's a priority at this stage.

the idea of checking for a stream and then piping it is a good one. we could even check for an iterator and convert it into a stream. in fact, we could assume that functions are iterator functions, but that is probably dragging too much of fairmont into the design of PBX.

@PandaWhisperer not sure why writing tests for this is problematic. just look at the existing tests and try responding with different data types. don't worry too much about writing “proper” tests. people get way too pedantic about testing. the main thing is to exercise the code you wrote. you can improve the tests once you have them, but start by being as simple and direct as possible.

**Comment by PandaWhisperer** [comment]
@dyoder I'm having difficulties because there are not existing tests for the context. I need a `request`, a `response`, and an `api` to create a context. The latter I can get from the builder, for the former I tried using [node-mocks-http](https://github.com/howardabrams/node-mocks-http). 

I tried setting up a simple test like this:

``` coffeescript
    context.test "Context", ->
      Context = require "../src/context"

      # we need to mock a request and response to use the context
      request = httpMocks.createRequest 
        method: 'GET'
        url: '/users'

      response = httpMocks.createResponse()

      ctx = Context.make request, response, builder.api
      ctx.respond 200, "Success"
```

However, this fails with the following error:

```
TypeError: Cannot read property 'schema' of undefined
  at Function.module.exports.Context.make (/Users/chris/Work/PandaStrike/pbx/src/context.coffee:12:29)
```

Apparently, the `validate` method is missing, because [it is injected by the processor](https://github.com/pandastrike/pbx/blob/master/src/processor.coffee#L20-L23) upon startup. Now what?

**Comment by PandaWhisperer** [comment]
Whoops. Looks like I screwed up there. `Context.make` takes only one parameter, so it should be

``` coffeescript
ctx = Context.make {request, response, api: builder.api}
```

**Comment by PandaWhisperer** [comment]
Alright, I figured out how to test this. Updated #13 with a brand new shiny test case.
