### ISSUE TITLE
Is It Possible to Determine the Request Protocol?

### ISSUE THREAD

**Issue by freeformflow** [pandastrike/pbx#26]
@dyoder, I'd like to examine the protocol (HTTP or HTTPS) of the incoming request to an API handler.  By using `context.request.headers.host`, I can retrieve everything _but_ the protocol.  I've looked at the example app and the rather large context object that handlers get, but nothing jumps out at me.

For the time being, I've got a work-around.  Is it just that PBX doesn't support protocol detection, or is it more fundamental to how this kind of messaging works?

**Comment by automatthew** [comment]
Protocol is part of the URL, not the headers.  If it's done the same as in Patchboard, it'll be `context.request.url`.

You can parse URLs with the stdlib "url" module.

``` coffee
url = require "url"

parsed = url.parse(context.request.url)
```

https://nodejs.org/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost

**Comment by automatthew** [comment]
I'm curious as to the use case for knowing the protocol.

**Comment by freeformflow** [comment]
@automatthew, thank you.  Unfortunately, `context.request.url` returns only the path.

**Example**
Full Address: `https://huxley.pandastrike.com:3030/cluster/fearless-panda`
What's returned from "context.request.url": `/cluster/fearless-panda` 

My use case is the Huxley API server.  While I'm doing testing, I'm just using the bare server under HTTP.  When we deploy it into production, it sits behind a load balancer with SSL termination, so you reach it via HTTPS.

This is something that could be handled with an env configuration, but I wanted to avoid that for now.  I was hoping I could make the handler flexible enough to figure out how it is being reached.  I have a work-around functioning for now.  Dan is making Mr. Burns jokes, so I'm just going to focus on getting my other changes deployed before he sets the dogs on me, haha.

**Comment by automatthew** [comment]
Oh, you're right.  Only the path is available.

I still don't understand why you need, within the application, to know the protocol used by the client.

**Comment by automatthew** [comment]
Here's how express attempts to figure out the request protocol:

https://github.com/strongloop/express/blob/master/lib/request.js#L265-L279

**Comment by freeformflow** [comment]
Oh, sorry.  I didn't explain that part.  The API server spawns EC2 clusters on command.  The library that handles that is called `panda-cluster`.  

To avoid a mingling of concerns, `panda-cluster` makes an PUT call back to the API server with progress updates.  The PUT handler is what interfaces with Huxley's database.  So, `panda-cluster` needs to know  the fully-formed address of the API server so it can call out to it.  
- When I create a cluster, I make a POST request to the API, which has a body field.  I stick the fully-formed address in there and everything works fine.  
- When I delete a cluster, I make a DELETE request, which does not have a body field.  That's where I'm running into trouble.

**Comment by freeformflow** [comment]
Hmm.  Thanks for that.  I'll look into replicating Express's method.  From my stumblings last night, I saw that the encryption field is null.  It would make sense that field would look different under https.

**Comment by automatthew** [comment]
Can you point me at the source code where you would use the req.protocol?

**Comment by freeformflow** [comment]
Oh, okay.  [This file](https://github.com/pandastrike/huxley/blob/development/alpha-06/huxley-api/src/api/handlers/cluster/delete.coffee) is the function that would take note of the protocol.  Once I have the fully formed URL, I'd place it into the panda-cluster configuration object [on this line](https://github.com/pandastrike/huxley/blob/development/alpha-06/huxley-api/src/api/handlers/cluster/delete.coffee#L33).  In the panda-cluster library, you can see I reference that object when I call out to the Huxley API [here](https://github.com/pandastrike/panda-cluster/blob/development/alpha-06/src/huxley.coffee#L16)

**Comment by dyoder** [comment]
@PandaPup the reason @automatthew is pressing you on this is that the URL ought to be entirely opaque. That is, you don't want to work around passing the URL directly. This unnecessarily increases the coupling between components.

The fact that there is a callback involved suggests this isn't a `DELETE`—there are side-effects. Thus, it should be a `POST`.

**Comment by freeformflow** [comment]
Oh.  Okay.  I can turn this into a POST pretty easily, and that will solve the immediate problem. @dyoder, you and I should talk about architecting status updates from panda-cluster to the API's database in the nearish future.  Thanks to both of you, I'm gonna close this as resolved then.
